name: Daily IDRC Funding Scraper

on:
  schedule:
    - cron: '0 8 * * *'   # Every day at 08:00 UTC
  workflow_dispatch:        # Allows manual run from UI

permissions:
  contents: write           # Needed to allow git commit/push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python scrape_idrc_funding.py

    - name: Debug output
      run: |
        echo "✅ Listing directory contents:"
        ls -lh

    - name: Commit and push results
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        if [ -f idrc_funding_opportunities_detailed.csv ]; then
          git add idrc_funding_opportunities_detailed.csv
          git add idrc_funding_opportunities_detailed.json
          git commit -m "Update scraped data on $(date)" || echo "No changes"
          git push
        else
          echo "❌ CSV file not found. Skipping commit."
        fi
