name: Daily IDRC Funding Scraper

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 08:00 UTC
  workflow_dispatch:      # Allow manual trigger

permissions:
  contents: write  # 👈 Required to allow git push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python scrape_idrc_funding.py

    - name: Commit and push results
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add idrc_funding_opportunities_detailed.csv
        git commit -m "Update scraped data [$(date)]" || echo "No changes"
        git push
